config/routes.rb
Rails.application.routes.draw do
  device_controllers = {
    registrations:  'front/devise_custom/registrations',
    sessions:       'front/devise_custom/sessions',
    passwords:      'front/devise_custom/passwords',
    confirmations:  'front/devise_custom/confirmations',
  }

  # 表画面
  scope module: :front do
    # トップ
    root 'homes#index'

    # devise
    devise_for :users, controllers: device_controllers, path: 'user', path_names: {
      sign_in:  'login',
      sign_out: 'logout',
    }
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end

    # 商品
    resources :items do
      member do
        get 'payment_confirm'
        patch 'payment'
        get 'payment_finish'
      end
      resources :destinations, only: %w(index new create destroy) do
        collection do
          patch 'destination_update'
        end
      end
      resources :creditcards, only: %w(index new create destroy) do
        collection do
          patch 'card_update'
        end
      end
      resources :comments, only: [:create, :destroy]
    end

    # 購入

    # カテゴリ
    resources :categories, only: :show

    # マイページ
    resources :settings, only: :index
    namespace :settings do
      resources :notices, only: :index
    end

    resources :articles, only: %w(index show)

    # API
    namespace :api, { format: 'json' } do
      resources :articles, only: :index
    end
  end

  # 管理画面
  namespace :admin do
    root 'homes#index'
    resources :items
    resources :categories do
      collection do
        get 'order_edit'
      end
    end
  end

  # api
  namespace :api, {format: 'json'} do
    resources :items, only: :index do
      resources :comments
    end
    resources :posts
    resources :chat_messages
  end
end

app/controllers/front/api/articles_controller.rb
class Front::Api::ArticlesController < ApplicationController
  # モジュール
  respond_to :json, :js


  # 定数
  INDEX_PER_ARTICLES = 30


  # メソッド
  def index
    @article_searcher = Article::Searcher.new(article_searcher_params)
    @articles = @article_searcher.search.page(params[:page]).per(params[:per_page] || INDEX_PER_ARTICLES)

    respond_with @articles
  end


  # メソッド(Private)
  private
  
  def article_searcher_params
    params.permit(Article::Searcher::attribute_names)
  end
end

app/controllers/front/articles_controller.rb
class Front::ArticlesController < FrontController
  # レイアウト


  # 定数


  # フック


  # メソッド
  def index
  end

  def show
  end


  # メソッド(Private)
end

app/controllers/front/categories_controller.rb
class Front::CategoriesController < FrontController
  # 定数
  INDEX_PER_ITEMS = 100


  # メソッド
  def show
    @category = Category.find(params[:id])
    @items = @category.items.order(created_at: :desc).page(params[:page])
            .per(params[:per_page] || INDEX_PER_ITEMS)
  end
end

app/controllers/front/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  def create
    @chat_message = current_user.chat_messages.create!(chat_message_params)
    ActionCable.server.broadcast 'chat_room_channel', chat_message: @chat_message.template
  end

  private
  def chat_message_params
    params.require(:chat_message).permit(:content)
  end
end

app/controllers/front/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  # 定数
  INDEX_PER_CHAT_ROOMS = 10

  def index
    @chat_rooms = current_user.chat_rooms
                  .page(params[:page]).per(params[:per_page] || INDEX_PER_CHAT_ROOMS)
                  .order(created_at: :desc)
    @chat_room = ChatRoom.new
    @chat_room.users << current_user
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    if @chat_room.save
      redirect_to chat_rooms_path, notice: 'チャットルーム作成ができました'
    else
      render :index
    end
  end

  def show
    # 投稿一覧表示に利用
    @chat_messages = ChatMessage.includes(:user).order(:id)
    # メッセージ投稿に利用
    @chat_message = current_user.chat_messages.new
  end

  def search
    @users = User.search(params[:keyword], current_user)
    render json: @users
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name, { user_ids: [] } )
  end
end

app/controllers/front/comments_controller.rb
class Front::CommentsController < FrontController
  # 定数
  PERMITTED_ATTRIBUTES = %i(user_id item_id body)


  # フック
  before_action :authenticate_user!, only: [:create, :destroy]


  # メソッド
  def create
    @comment = current_user.comments.build(comment_params)
    item = @comment.item

    respond_to do |format|
      if @comment.save
        format.html { redirect_to item_path(item) } 
        format.js
        seller = @comment.item.user
        seller.notices.generate_by(:create_comment, @comment).save!
      else
        format.html { redirect_to item_path(item) } 
        format.js
      end
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(*PERMITTED_ATTRIBUTES)
  end
end

app/controllers/front/creditcards_controller.rb
class Front::CreditcardsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @creditcards = current_user.creditcards.without_deleted
  end

  def new
    @creditcard = Creditcard.new
  end

  def create
    # 顧客IDがなければ顧客オブジェクトを作成
    if current_user.stripe_customer_id.blank?
      res = Stripe::Customer.create
      current_user.update!(stripe_customer_id: res.id)
    end

    # クレカオブジェクトを作成
    res = Stripe::Customer.create_source(
      current_user.stripe_customer_id,
      { source: params[:token] },
    )

    new_card = current_user.creditcards.create!(
      status: 'available',
      stripe_creditcard_id: res.id,
      masked_number: ('*' * 12) + res.last4,
      expire_date: Creditcard.parse_expire_date(res.exp_month, res.exp_year),
      brand: res.brand,
    )

    current_user.update!(selected_creditcard_id: new_card.id)
    flash[:success] = 'クレジットカードを登録しました。'
    redirect_to payment_confirm_item_path(@item)

  rescue Stripe::CardError => e
    flash[:danger] = e.message
    redirect_to action: :new
  end

  def card_update
    if current_user.update(user_params)
      flash[:success] = '選択クレジットカードを変更しました。'
      redirect_to payment_confirm_item_path(@item)
    else
      flash.now[:danger] = '選択クレジットカードを変更できませんでした。'
      render :index
    end
  end

  def destroy
    creditcards = current_user.creditcards.without_deleted
    creditcard = creditcards.find(params[:id])

    # クレカオブジェクトを削除
    res = Stripe::Customer.delete_source(
      current_user.stripe_customer_id,
      creditcard.stripe_creditcard_id,
    )

    # クレカを論理削除
    if creditcard.logical_delete
      if current_user.selected_creditcard_id == creditcard.id
        current_user.update!(selected_creditcard_id: nil)
      end
      flash[:success] = 'クレジットカードを削除しました。'
    else
      flash[:alert] = 'クレジットカードを削除できませんでした。'
    end

    # クレカが全て論理削除されたらクレカ新規登録画面に遷移
    if creditcards.where(deleted_at: nil).empty?
      redirect_to new_item_creditcard_path(@item)
    else
      redirect_to item_creditcards_path(@item)
    end

  rescue Stripe::CardError => e
    flash[:danger] = e.message
    redirect_to action: :index
  end

  private

  def user_params
    params.require(:user).permit(:selected_creditcard_id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/destinations_controller.rb
class Front::DestinationsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @destinations = current_user.destinations
  end

  def new
    @destination = Destination.new
  end

  def create
  end

  def destination_update
    if current_user.update(user_params)
      flash[:success] = '選択配送先を変更しました。'
      redirect_to payments_confirm_path(item_id: @item.id)
    else
      flash.now[:danger] = '選択配送先を変更できませんでした。'
      render :index
    end
  end

  def destroy
    destinations = current_user.destinations
    destination = destinations.find(params[:id])

    if destination.destroy
      flash[:success] = '配送先を削除しました。'
    else
      flash[:alert] = '配送先を削除できませんでした。'
    end

    # 配送先が全て削除されたら配送先新規登録画面に遷移
    if destinations.exists?
      redirect_to payments_destination_path(item_id: @item.id)
    else
      redirect_to new_payments_destination_path(item_id: @item.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:selected_destination_id)
  end


  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/devise_custom/passwords_controller.rb
class Front::DeviseCustom::PasswordsController < Devise::PasswordsController
  layout 'front'
  
  before_action :check_guest, only: :create
end

app/controllers/front/devise_custom/registrations_controller.rb
class Front::DeviseCustom::RegistrationsController < Devise::RegistrationsController
  layout 'front'
  
  before_action :check_guest, only: %i[update destroy]
end

app/controllers/front/devise_custom/sessions_controller.rb
class Front::DeviseCustom::SessionsController < Devise::SessionsController
  layout 'front'

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/front/homes_controller.rb
class Front::HomesController < FrontController
  def index
    @categories = Category.includes(:items).first(4)
  end
end

app/controllers/front/items_controller.rb
class Front::ItemsController < FrontController
  # レイアウト
  layout 'front_modal', only: :payment_confirm


  # 定数
  INDEX_PER_ITEMS = 50
  PERMITTED_ATTRIBUTES = %i(category_id name body price condition delivery_fee sales_status note)
  NESTED_ATTRIBUTES = %i(id item_id image)


  # フック
  before_action :set_category, only: :index
  before_action :authenticate_user!, only: [:new, :create, :payment_confirm, :payments, :payment_finish]
  before_action :set_item, only: [:payment_confirm, :payment]


  # メソッド
  def index
    @category = Category.find_by(id: params[:category_id])
    @item_searcher = Item::Searcher.new(item_searcher_params)
    order = Item::FRONT_ORDERS[params[:item_order]] || { created_at: :desc }
    @items = @item_searcher.search.order(order).page(params[:page]).per(params[:per_page] || INDEX_PER_ITEMS)
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to items_path, notice: '商品を出品しました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @other_items = @item.user.items.order(created_at: :desc).limit(6)
  end

  def payment_confirm
    if current_user.selected_creditcard_id.present?
      @selected_creditcard = current_user.creditcards.without_deleted.find(current_user.selected_creditcard_id)
    end
    if current_user.selected_destination_id.present?
      @selected_destination = current_user.destinations.find(current_user.selected_destination_id)
    end
  end

  def payment
    if current_user.selected_creditcard.status == 'unavailable'
      flash[:danger] = '無効なクレジットカードです。'
      render :payment_confirm
      return
    end

    payment = current_user.payments.create!(
      creditcard_id: current_user.selected_creditcard_id,
      item_id: @item.id,
      price: @item.price,
    )

    # stripeに課金
    res = Stripe::Charge.create({
      amount: @item.price,
      currency: "jpy",
      customer: current_user.stripe_customer_id,
      source: current_user.selected_creditcard.stripe_creditcard_id,
    })

    redirect_to payment_finish_item_path(@item)

  rescue Stripe::CardError => e
    payment.update!(
      status: 'error',
      result_code: '',
      error_message: '',
    )
    flash[:danger] = e.message
    render :payment_confirm
  end

  def payment_finish
  end


  # メソッド(Private)
  private

  def item_params
    params.require(:item).permit(*PERMITTED_ATTRIBUTES, item_images_attributes: [:id, :item_id, :image])
  end

  def set_category
    @category = Category.find(params[:category_id]) if params[:category_id].present?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_searcher_params
    params.permit(Item::Searcher::STRONG_PARAMETER)
  end
end

app/controllers/front/payments/creditcards_controller.rb
class Front::Payments::CreditcardsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @creditcards = current_user.creditcards.without_deleted
  end

  def new
    @creditcard = Creditcard.new
  end

  def new
  end

  def create
    # 顧客IDがなければ顧客オブジェクトを作成
    if current_user.stripe_customer_id.blank?
      res = Stripe::Customer.create
      current_user.update!(stripe_customer_id: res.id)
    end

    # クレカオブジェクトを作成
    res = Stripe::Customer.create_source(
      current_user.stripe_customer_id,
      { source: params[:token] },
    )

    new_card = current_user.creditcards.create!(
      stripe_creditcard_id: res.id,
      expire_date: Creditcard.parse_expire_date(res.exp_month, res.exp_year),
      masked_number: res.last4,
    )

    current_user.update!(selected_creditcard_id: new_card.id)
    flash[:success] = 'クレジットカードを登録しました。'
    redirect_to payments_confirm_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to action: :new
  end

  def card_update
    if current_user.update(user_params)
      flash[:success] = '選択クレジットカードを変更しました。'
      redirect_to payments_confirm_path(item_id: @item.id)
    else
      flash.now[:danger] = '選択クレジットカードを変更できませんでした。'
      render :index
    end
  end

  def destroy
    creditcards = current_user.creditcards.without_deleted
    creditcard = creditcards.find(params[:id])

    if creditcard.logical_delete
      if current_user.selected_creditcard_id == creditcard.id
        current_user.update!(selected_creditcard_id: nil)
      end
      flash[:success] = 'クレジットカードを削除しました。'
    else
      flash[:alert] = 'クレジットカードを削除できませんでした。'
    end

    # クレカが全て論理削除されたらクレカ新規登録画面に遷移
    if creditcards.where(deleted_at: nil).empty?
      redirect_to new_payments_creditcard_path(item_id: @item.id)
    else
      redirect_to payments_creditcard_path(item_id: @item.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:selected_creditcard_id)
  end


  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/payments/destinations_controller.rb
class Front::Payments::DestinationsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @destinations = current_user.destinations
  end

  def new
    @destination = Destination.new
  end

  def create
  end

  def destination_update
    if current_user.update(user_params)
      flash[:success] = '選択配送先を変更しました。'
      redirect_to payments_confirm_path(item_id: @item.id)
    else
      flash.now[:danger] = '選択配送先を変更できませんでした。'
      render :index
    end
  end

  def destroy
    destinations = current_user.destinations
    destination = destinations.find(params[:id])

    if destination.destroy
      flash[:success] = '配送先を削除しました。'
    else
      flash[:alert] = '配送先を削除できませんでした。'
    end

    # 配送先が全て削除されたら配送先新規登録画面に遷移
    if destinations.exists?
      redirect_to payments_destination_path(item_id: @item.id)
    else
      redirect_to new_payments_destination_path(item_id: @item.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:selected_destination_id)
  end


  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/settings/notices_controller.rb
class Front::Settings::NoticesController < Front::SettingsController
  # 定数
  INDEX_PER_WORKS = 50


  # メソッド
  def index
    @notices = current_user.notices
             .page(params[:page]).per(params[:per_page] || INDEX_PER_WORKS)
             .order(created_at: :desc)
  end
end

app/controllers/front/settings_controller.rb
class Front::SettingsController < FrontController
  before_action :authenticate_user!

  # メソッド
  def index
    @notices = current_user.notices.order(created_at: :desc).limit(5)
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  layout 'front'
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_notices, if: :user_signed_in?

  def check_guest
    email = resource&.email || params[:user][:email].downcase
    if email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [ :name, :email, :password, :password_confirmation　]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private

  def set_notices
    @notices = current_user.notices.includes(:sender).order(id: :desc).limit(5)
  end
end

app/views/front/shared/_flash_item.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/front/shared/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/front/shared/_footer.html.erb
<footer class="bg-dark mt-5" style="max-width: 100%; height: 300px;">
</footer>

app/views/front/shared/_header.html.erb
<header class="mb-3" style="height: 100px; background-color: white;">
  <div class="container">
    <nav class="navbar navbar-expand-lg ">
      <%= link_to 'フリマアプリ', root_path, class: 'navbar-brand text-dark font-weight-bold' %>
      <%= form_with url: items_path, method: "get", class: 'form-group m-0', local: true do |f| %>
        <%= f.text_field :keywords, value: params[:keywords], placeholder: '何かお探しですか？', class: 'form-control form-control-sm', style: 'width: 950px' %>
      <% end %>
    </nav>
    <nav class="navbar navbar-expand-lg p-0">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'カテゴリから探す', '#', class: 'nav-link text-dark font-weight-bold' %>
        </li>
        <li class="nav-item">
          <%= link_to 'ブランドから探す', '#', class: 'nav-link text-dark font-weight-bold' %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'いいね一覧', '#', class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to settings_notices_path, class: 'nav-link dropdown-toggle text-dark', id: 'navbarDropdown' do %>
              お知らせ
            <% end %>
            <div class="dropdown-menu mt-0" aria-labelledby="navbarDropdown">
              <% @notices.each do |notice| %>
                <%= link_to '#', id: "notice-#{notice.id}", class: "js-navbar-notification-dropdown-item dropdown-item" do %>
                  <div class="d-flex align-items-center">
                    <div class="text-center mr-3">
                      <%# image = notice.sender_id? ? notice.sender_image.url(:thumb) : 'no-image.jpg' %>
                      <%= image_tag 'no-image.jpg', style: 'height: 50px; width: 50px;' %>
                    </div>
                    <div>
                      <div class="text-wrap">
                        <p style="font-size: 0.8rem;"><%= raw notice.body %></p>
                      </div>
                      <div class="text-muted">
                        <p style="font-size: 0.7rem;"><%= time_ago_in_words(notice.created_at) %>前</p>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to 'やることリスト', '#', class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item">
            <%= link_to 'マイページ', settings_path, class: 'nav-link text-dark' %>
          </li>
          <li class="nav-item active">
            <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link btn btn-danger btn-sm' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "新規会員登録", new_user_registration_path, class: 'btn btn-danger btn-sm mr-2' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'btn btn-outline-primary btn-sm mr-2' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: 'btn btn-outline-primary btn-sm' %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/front/shared/_stripe_checkout.html.erb
<script src="https://js.stripe.com/v3/"></script>

<div>
  <%= form_with url: item_creditcards_path(@item), id: 'payment-form', method: :post, local: true do |f| %>
    <%= hidden_field_tag :token %>

    <div class="mb-5">
      <label for="card-number-element">カード番号</label>
      <span class="badge badge-danger">必須</span>
      <div id="card-number-element"></div>
      <div id="cardNumber-error" class="mt-2"></div>
    </div>

    <div class="mb-5">
      <label for="card-expiry-element">有効期限</label>
      <span class="badge badge-danger">必須</span>
      <div id="card-expiry-element"></div>
      <div id="cardExpiry-error" class="mt-2"></div>
    </div>

    <div class="mb-5">
      <label for="card-cvc-element">セキュリティーコード</label>
      <span class="badge badge-danger">必須</span>
      <div id="card-cvc-element"></div>
      <div id="cardCvc-error" class="mt-2"></div>
    </div>

    <div class="mt-5">
      <div id="card-error" style="word-wrap:break-all;"></div>
      <div id="result-message" style="word-wrap:break-all;"></div>
    </div>

    <%= button_tag type: 'submit', id: 'card_btn', class: 'btn btn-danger btn-block mt-5', onclick: 'createCard()' do %>
      <span id="button-text">登録する</span>
    <% end %>
  <% end %>
</div>

<script>
// 変数定義
var stripe = Stripe("<%= Rails.configuration.stripe[:public_key] %>");
var elements = stripe.elements();
var cardNumberElement = elements.create('cardNumber', {
  showIcon: true,
  placeholder: '例）1234 5678 9012 3456'
});
var cardExpiryElement = elements.create('cardExpiry', {
  placeholder: '01 / 20'
});
var cardCvcElement = elements.create('cardCvc', {
  placeholder: '123'
});
var cardBtn = document.getElementById('card_btn');
var form = document.getElementById('payment-form');
var cardError = document.getElementById('card-error');
var resultMsg = document.getElementById('result-message');
var token = document.getElementById('token');


// ボタン初期表示
cardBtn.disabled = true;


// stripeのクレカフォームをDOMに挿入
cardNumberElement.mount('#card-number-element');
cardExpiryElement.mount('#card-expiry-element');
cardCvcElement.mount('#card-cvc-element');


// フォームバリデータ
var formValidator = function(event) {
  var errorContainer = document.getElementById(event.elementType + "-error")
  if (event.error) {
    errorContainer.textContent = event.error.message;
    errorContainer.style.color = "red"
  } else {
    errorContainer.textContent = ""
    cardBtn.disabled = event.empty;
  }
}


// 入力に反応
cardNumberElement.on('change', formValidator);
cardCvcElement.on('change', formValidator);
cardExpiryElement.on('change', formValidator);


// カード登録
function createCard(e) {
  event.preventDefault();
  loading(true);
  stripe.createToken(cardNumberElement).then(error_handler)
};


// 処理中
var loading = function(isLoading) {
  if (isLoading) {
    cardBtn.disabled = true;
  } else {
    cardBtn.disabled = false;
  }
};


// エラーハンドラ
var error_handler = function(result) {
  if (result.error) {
    loading(false);
    cardError.textContent = result.error.message;
    cardError.style.color = "red";
  } else {
    loading(false);
    cardBtn.disabled = true;
    token.value = result.token.id;
    resultMsg.textContent = "成功";
    resultMsg.style.color = "green";
    form.submit();
  }
}
</script>