config/routes.rb
Rails.application.routes.draw do
  device_controllers = {
    registrations:  'front/devise_custom/registrations',
    sessions:       'front/devise_custom/sessions',
    passwords:      'front/devise_custom/passwords',
    confirmations:  'front/devise_custom/confirmations',
  }

  # 表画面
  scope module: :front do
    # トップ
    root 'homes#index'

    # devise
    devise_for :users, controllers: device_controllers, path: 'user', path_names: {
      sign_in:  'login',
      sign_out: 'logout',
    }
    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#new_guest'
    end

    # 商品
    resources :items do
      member do
        get 'payment_confirm'
        patch 'payment'
        get 'payment_finish'
      end
      resources :destinations, only: %w(index new create destroy) do
        collection do
          patch 'destination_update'
        end
      end
      resources :creditcards, only: %w(index new create destroy) do
        collection do
          patch 'card_update'
        end
      end
      resources :comments, only: [:create, :destroy]
    end

    # 購入

    # カテゴリ
    resources :categories, only: :show

    # マイページ
    resources :settings, only: :index
    namespace :settings do
      resources :notices, only: :index
    end

    resources :articles, only: %w(index show)

    # API
    namespace :api, { format: 'json' } do
      resources :articles, only: :index
    end
  end

  # 管理画面
  namespace :admin do
    root 'homes#index'
    resources :items
    resources :categories do
      collection do
        get 'order_edit'
      end
    end
  end

  # api
  namespace :api, {format: 'json'} do
    resources :items, only: :index do
      resources :comments
    end
    resources :posts
    resources :chat_messages
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < AdminController
  # 定数
  INDEX_PER_ITEMS = 10
  PERMITTED_ATTRIBUTES = %i(name body price condition image note)


  # フック


  # メソッド
  def index
    one = search_items
    @csv_data = one
    @items = one.page(params[:page]).per(params[:per_page] || INDEX_PER_ITEMS)

    respond_to do |format|
      format.html do
        @items
      end 
      format.csv do
        send_data render_to_string, filename: "(ファイル名).csv", type: :csv
      end
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to items_path, notice: '商品を出品しました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end


  # メソッド(Private)
  private

  def search_items
    one = Item.all
    
    # 絞込
    one = one.where('items.name LIKE ?', '%' + params[:name] + '%') if params[:name].present?
    one = one.where('items.body LIKE ?', '%' + params[:body] + '%') if params[:body].present?
    one = one.where('items.price LIKE ?', '%' + params[:price] + '%') if params[:price].present?
    # one = one.where(condition: params[:condition]) if params[:condition].present?

    # # ソート
    # one = one.order(created_at: :desc) if params[:sort_order] == 'created_desc'
    # one = one.order(price: :asc) if params[:sort_order] == 'price_asc'
    # one = one.order(price: :desc) if params[:sort_order] == 'price_desc'

    one
  end

  def item_params
    params.require(:item).permit(*PERMITTED_ATTRIBUTES)
  end
end

app/controllers/front/api/articles_controller.rb
class Front::Api::ArticlesController < ApplicationController
  # モジュール
  respond_to :json, :js


  # 定数
  INDEX_PER_ARTICLES = 30


  # メソッド
  def index
    @article_searcher = Article::Searcher.new(article_searcher_params)
    @articles = @article_searcher.search.page(params[:page]).per(params[:per_page] || INDEX_PER_ARTICLES)

    respond_with @articles
  end


  # メソッド(Private)
  private
  
  def article_searcher_params
    params.permit(Article::Searcher::attribute_names)
  end
end

app/controllers/front/articles_controller.rb
class Front::ArticlesController < FrontController
  # レイアウト


  # 定数


  # フック


  # メソッド
  def index
  end

  def show
  end


  # メソッド(Private)
end

app/controllers/front/categories_controller.rb
class Front::CategoriesController < FrontController
  # 定数
  INDEX_PER_ITEMS = 100


  # メソッド
  def show
    @category = Category.find(params[:id])
    @items = @category.items.order(created_at: :desc).page(params[:page])
            .per(params[:per_page] || INDEX_PER_ITEMS)
  end
end

app/controllers/front/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  def create
    @chat_message = current_user.chat_messages.create!(chat_message_params)
    ActionCable.server.broadcast 'chat_room_channel', chat_message: @chat_message.template
  end

  private
  def chat_message_params
    params.require(:chat_message).permit(:content)
  end
end

app/controllers/front/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  # 定数
  INDEX_PER_CHAT_ROOMS = 10

  def index
    @chat_rooms = current_user.chat_rooms
                  .page(params[:page]).per(params[:per_page] || INDEX_PER_CHAT_ROOMS)
                  .order(created_at: :desc)
    @chat_room = ChatRoom.new
    @chat_room.users << current_user
  end

  def create
    @chat_room = ChatRoom.new(chat_room_params)
    if @chat_room.save
      redirect_to chat_rooms_path, notice: 'チャットルーム作成ができました'
    else
      render :index
    end
  end

  def show
    # 投稿一覧表示に利用
    @chat_messages = ChatMessage.includes(:user).order(:id)
    # メッセージ投稿に利用
    @chat_message = current_user.chat_messages.new
  end

  def search
    @users = User.search(params[:keyword], current_user)
    render json: @users
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:name, { user_ids: [] } )
  end
end

app/controllers/front/comments_controller.rb
class Front::CommentsController < FrontController
  # 定数
  PERMITTED_ATTRIBUTES = %i(user_id item_id body)


  # フック
  before_action :authenticate_user!, only: [:create, :destroy]


  # メソッド
  def create
    @comment = current_user.comments.build(comment_params)
    item = @comment.item

    respond_to do |format|
      if @comment.save
        format.html { redirect_to item_path(item) } 
        format.js
        seller = @comment.item.user
        seller.notices.generate_by(:create_comment, @comment).save!
      else
        format.html { redirect_to item_path(item) } 
        format.js
      end
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(*PERMITTED_ATTRIBUTES)
  end
end

app/controllers/front/creditcards_controller.rb
class Front::CreditcardsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @creditcards = current_user.creditcards.without_deleted
  end

  def new
    @creditcard = Creditcard.new
  end

  def create
    # 顧客IDがなければ顧客オブジェクトを作成
    if current_user.stripe_customer_id.blank?
      res = Stripe::Customer.create
      current_user.update!(stripe_customer_id: res.id)
    end

    # クレカオブジェクトを作成
    res = Stripe::Customer.create_source(
      current_user.stripe_customer_id,
      { source: params[:token] },
    )

    new_card = current_user.creditcards.create!(
      status: 'available',
      stripe_creditcard_id: res.id,
      masked_number: ('*' * 12) + res.last4,
      expire_date: Creditcard.parse_expire_date(res.exp_month, res.exp_year),
      brand: res.brand,
    )

    current_user.update!(selected_creditcard_id: new_card.id)
    flash[:success] = 'クレジットカードを登録しました。'
    redirect_to payment_confirm_item_path(@item)

  rescue Stripe::CardError => e
    flash[:danger] = e.message
    redirect_to action: :new
  end

  def card_update
    if current_user.update(user_params)
      flash[:success] = '選択クレジットカードを変更しました。'
      redirect_to payment_confirm_item_path(@item)
    else
      flash.now[:danger] = '選択クレジットカードを変更できませんでした。'
      render :index
    end
  end

  def destroy
    creditcards = current_user.creditcards.without_deleted
    creditcard = creditcards.find(params[:id])

    # クレカオブジェクトを削除
    res = Stripe::Customer.delete_source(
      current_user.stripe_customer_id,
      creditcard.stripe_creditcard_id,
    )

    # クレカを論理削除
    if creditcard.logical_delete
      if current_user.selected_creditcard_id == creditcard.id
        current_user.update!(selected_creditcard_id: nil)
      end
      flash[:success] = 'クレジットカードを削除しました。'
    else
      flash[:alert] = 'クレジットカードを削除できませんでした。'
    end

    # クレカが全て論理削除されたらクレカ新規登録画面に遷移
    if creditcards.where(deleted_at: nil).empty?
      redirect_to new_item_creditcard_path(@item)
    else
      redirect_to item_creditcards_path(@item)
    end

  rescue Stripe::CardError => e
    flash[:danger] = e.message
    redirect_to action: :index
  end

  private

  def user_params
    params.require(:user).permit(:selected_creditcard_id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/destinations_controller.rb
class Front::DestinationsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @destinations = current_user.destinations
  end

  def new
    @destination = Destination.new
  end

  def create
  end

  def destination_update
    if current_user.update(user_params)
      flash[:success] = '選択配送先を変更しました。'
      redirect_to payments_confirm_path(item_id: @item.id)
    else
      flash.now[:danger] = '選択配送先を変更できませんでした。'
      render :index
    end
  end

  def destroy
    destinations = current_user.destinations
    destination = destinations.find(params[:id])

    if destination.destroy
      flash[:success] = '配送先を削除しました。'
    else
      flash[:alert] = '配送先を削除できませんでした。'
    end

    # 配送先が全て削除されたら配送先新規登録画面に遷移
    if destinations.exists?
      redirect_to payments_destination_path(item_id: @item.id)
    else
      redirect_to new_payments_destination_path(item_id: @item.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:selected_destination_id)
  end


  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/devise_custom/passwords_controller.rb
class Front::DeviseCustom::PasswordsController < Devise::PasswordsController
  layout 'front'
  
  before_action :check_guest, only: :create
end

app/controllers/front/devise_custom/registrations_controller.rb
class Front::DeviseCustom::RegistrationsController < Devise::RegistrationsController
  layout 'front'
  
  before_action :check_guest, only: %i[update destroy]
end

app/controllers/front/devise_custom/sessions_controller.rb
class Front::DeviseCustom::SessionsController < Devise::SessionsController
  layout 'front'

  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/front/homes_controller.rb
class Front::HomesController < FrontController
  def index
    @categories = Category.includes(:items).first(4)
  end
end

app/controllers/front/items_controller.rb
class Front::ItemsController < FrontController
  # レイアウト
  layout 'front_modal', only: :payment_confirm


  # 定数
  INDEX_PER_ITEMS = 50
  PERMITTED_ATTRIBUTES = %i(category_id name body price condition delivery_fee sales_status note)
  NESTED_ATTRIBUTES = %i(id item_id image)


  # フック
  before_action :set_category, only: :index
  before_action :authenticate_user!, only: [:new, :create, :payment_confirm, :payments, :payment_finish]
  before_action :set_item, only: [:payment_confirm, :payment]


  # メソッド
  def index
    @category = Category.find_by(id: params[:category_id])
    @item_searcher = Item::Searcher.new(item_searcher_params)
    order = Item::FRONT_ORDERS[params[:item_order]] || { created_at: :desc }
    @items = @item_searcher.search.order(order).page(params[:page]).per(params[:per_page] || INDEX_PER_ITEMS)
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to items_path, notice: '商品を出品しました。'
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @other_items = @item.user.items.order(created_at: :desc).limit(6)
  end

  def payment_confirm
    if current_user.selected_creditcard_id.present?
      @selected_creditcard = current_user.creditcards.without_deleted.find(current_user.selected_creditcard_id)
    end
    if current_user.selected_destination_id.present?
      @selected_destination = current_user.destinations.find(current_user.selected_destination_id)
    end
  end

  def payment
    if current_user.selected_creditcard.status == 'unavailable'
      flash[:danger] = '無効なクレジットカードです。'
      render :payment_confirm
      return
    end

    payment = current_user.payments.create!(
      creditcard_id: current_user.selected_creditcard_id,
      item_id: @item.id,
      price: @item.price,
    )

    # stripeに課金
    res = Stripe::Charge.create({
      amount: @item.price,
      currency: "jpy",
      customer: current_user.stripe_customer_id,
      source: current_user.selected_creditcard.stripe_creditcard_id,
    })

    redirect_to payment_finish_item_path(@item)

  rescue Stripe::CardError => e
    payment.update!(
      status: 'error',
      result_code: '',
      error_message: '',
    )
    flash[:danger] = e.message
    render :payment_confirm
  end

  def payment_finish
  end


  # メソッド(Private)
  private

  def item_params
    params.require(:item).permit(*PERMITTED_ATTRIBUTES, item_images_attributes: [:id, :item_id, :image])
  end

  def set_category
    @category = Category.find(params[:category_id]) if params[:category_id].present?
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_searcher_params
    params.permit(Item::Searcher::STRONG_PARAMETER)
  end
end

app/controllers/front/payments/creditcards_controller.rb
class Front::Payments::CreditcardsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @creditcards = current_user.creditcards.without_deleted
  end

  def new
    @creditcard = Creditcard.new
  end

  def new
  end

  def create
    # 顧客IDがなければ顧客オブジェクトを作成
    if current_user.stripe_customer_id.blank?
      res = Stripe::Customer.create
      current_user.update!(stripe_customer_id: res.id)
    end

    # クレカオブジェクトを作成
    res = Stripe::Customer.create_source(
      current_user.stripe_customer_id,
      { source: params[:token] },
    )

    new_card = current_user.creditcards.create!(
      stripe_creditcard_id: res.id,
      expire_date: Creditcard.parse_expire_date(res.exp_month, res.exp_year),
      masked_number: res.last4,
    )

    current_user.update!(selected_creditcard_id: new_card.id)
    flash[:success] = 'クレジットカードを登録しました。'
    redirect_to payments_confirm_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to action: :new
  end

  def card_update
    if current_user.update(user_params)
      flash[:success] = '選択クレジットカードを変更しました。'
      redirect_to payments_confirm_path(item_id: @item.id)
    else
      flash.now[:danger] = '選択クレジットカードを変更できませんでした。'
      render :index
    end
  end

  def destroy
    creditcards = current_user.creditcards.without_deleted
    creditcard = creditcards.find(params[:id])

    if creditcard.logical_delete
      if current_user.selected_creditcard_id == creditcard.id
        current_user.update!(selected_creditcard_id: nil)
      end
      flash[:success] = 'クレジットカードを削除しました。'
    else
      flash[:alert] = 'クレジットカードを削除できませんでした。'
    end

    # クレカが全て論理削除されたらクレカ新規登録画面に遷移
    if creditcards.where(deleted_at: nil).empty?
      redirect_to new_payments_creditcard_path(item_id: @item.id)
    else
      redirect_to payments_creditcard_path(item_id: @item.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:selected_creditcard_id)
  end


  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/payments/destinations_controller.rb
class Front::Payments::DestinationsController < FrontMemberController
  layout 'front_modal'

  before_action :set_item

  # メソッド
  def index
    @destinations = current_user.destinations
  end

  def new
    @destination = Destination.new
  end

  def create
  end

  def destination_update
    if current_user.update(user_params)
      flash[:success] = '選択配送先を変更しました。'
      redirect_to payments_confirm_path(item_id: @item.id)
    else
      flash.now[:danger] = '選択配送先を変更できませんでした。'
      render :index
    end
  end

  def destroy
    destinations = current_user.destinations
    destination = destinations.find(params[:id])

    if destination.destroy
      flash[:success] = '配送先を削除しました。'
    else
      flash[:alert] = '配送先を削除できませんでした。'
    end

    # 配送先が全て削除されたら配送先新規登録画面に遷移
    if destinations.exists?
      redirect_to payments_destination_path(item_id: @item.id)
    else
      redirect_to new_payments_destination_path(item_id: @item.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:selected_destination_id)
  end


  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/front/settings/notices_controller.rb
class Front::Settings::NoticesController < Front::SettingsController
  # 定数
  INDEX_PER_WORKS = 50


  # メソッド
  def index
    @notices = current_user.notices
             .page(params[:page]).per(params[:per_page] || INDEX_PER_WORKS)
             .order(created_at: :desc)
  end
end

app/controllers/front/settings_controller.rb
class Front::SettingsController < FrontController
  before_action :authenticate_user!

  # メソッド
  def index
    @notices = current_user.notices.order(created_at: :desc).limit(5)
  end
end

app/views/front/items/_item.html.erb
<div class="col-md-3 mb-3">
  <%= link_to item_path(item), class: 'text-dark text-decoration-none' do %>
    <div class="card">
      <%= image_tag item.thumbnail, class: 'card-img', style: 'height: 150px;' %>
      <div class="card-body">
        <span>¥<%= item.price %></span>
        <p class="card-title"><%= item.name %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/front/items/index.html.erb
<div class="row mt-5">
  <%= render 'item_filter' %>
  <div class="col-sm-8">

    <!-- result -->
    <%
      result_from = (@items.current_page - 1)*@items.limit_value + 1
      result_to = @items.last_page? ? @items.total_count : @items.current_page*@items.limit_value
      result_total = @items.total_count
    %>

    <% if params[:keyword].present? %>
      <div class="mb-3 text-left">
        <span class="font-weight-bold"><%= params[:keyword] %></span> の検索結果
      </div>
    <% end %>

    <%= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>

    <div class="mb-3 text-left">
      <%= result_from %>〜<%= result_to  %>件表示（<%= result_total %>件中）
    </div>
    <!-- end result -->

    <div class="row">
      <%= render partial: 'item', collection: @items %>
    </div>

    <!-- paginate -->
    <%= paginate @items %>
    <!-- end paginate -->

  </div>
</div>

<script>
  jQuery(function($){
    // 並び替えselect
    $('#item-order-select').on('change', function(event) {
      var selected = $(this).val();
      var $itemOrder = $('#item-order');
      $itemOrder.val(selected);
      $itemOrder.closest('form').submit();
    });
  });
</script>

app/views/front/items/new.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2 rounded p-5" style="background-color: #FFFFFF;">
    <%= render 'front/shared/flash_item' %>
    <%= form_with model: @item, local: true do |f| %>

      <%= f.fields_for :item_images, @item.item_images.build do |ff| %>
        <div class="form-group">
          <%= ff.label :image %>
          <span class="badge badge-danger">必須</span>
          <p>最大10枚までアップロードできます</p>
          <%= ff.file_field :image %>
        </div>
      <% end %>

      <hr class="my-5">

      <div class="form-group">
        <%= f.label :name %>
        <span class="badge badge-danger">必須</span>
        <%= f.text_field :name, class: 'form-control', placeholder: '40文字まで' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <span class="badge badge-danger">必須</span>
        <%= f.text_area :body, class: 'form-control', rows: '5', placeholder: '商品の説明（必須 1,000文字以内）' %>
      </div>

      <hr class="my-5">

      <p class="mb-4">商品の詳細</p>
      <div class="form-group">
        <%= f.label :category_id %>
        <span class="badge badge-danger">必須</span>
        <%= f.select :category_id, options_from_collection_for_select(Category.all, :id, :name), { include_blank: '選択してください' }, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :condition %>
        <span class="badge badge-danger">必須</span>
        <%= f.select :condition, Item.condition.options, { include_blank: '選択してください' }, class: 'form-control' %>
      </div>

      <hr class="my-5">

      <p class="mb-4">配送について</p>
      <div class="form-group">
        <%= f.label :delivery_fee %>
        <span class="badge badge-danger">必須</span>
        <%= f.select :delivery_fee, Item.delivery_fee.options, { include_blank: '選択してください' }, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :prefecture %>
        <span class="badge badge-danger">必須</span>
        <%= f.select :prefecture, Item.prefecture.options, { include_blank: '選択してください' }, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :days_to_ship %>
        <span class="badge badge-danger">必須</span>
        <%= f.select :days_to_ship, Item.days_to_ship.options, { include_blank: '選択してください' }, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :sales_status %>
        <%= f.select :sales_status, Item.sales_status.options, { include_blank: '選択してください' }, class: 'form-control' %>
      </div>

      <hr class="my-5">

      <p class="mb-4">価格（¥300〜9,999,999）</p>
      <div class="form-group">
        <%= f.label :price %>
        <span class="badge badge-danger">必須</span>
        <%= f.number_field :price, class: 'form-control', placeholder: '数字で入力してください' %>
      </div>

      <%= f.submit '出品する', class: "btn btn-primary btn-block mt-5" %>

    <% end %>
  </div>
</div>

app/views/front/items/payment_confirm.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2 rounded p-5" style="background-color: #FFFFFF;">
    <div class="col-md-8 offset-md-2">
      <h2 class="text-center">購入内容の確認</h2>

      <hr class="my-5">

      <div class="row">
        <div class="col-md-3">
          <%= image_tag @item.thumbnail, class: 'card-img', style: 'width: 70px; height: 70px;' %>
        </div>
        <div class="col-md-9">
          <p><%= @item.name %></p>
          <p class="text-right">送料込み(税込) <span class="font-weight-bold">¥<%= @item.price %></span></p>
        </div>
      </div>

      <hr class="my-5">

      <div class="d-flex justify-content-between">
        <div><span class="font-weight-bold">支払い金額</span></div>
        <div><span class="font-weight-bold">¥<%= @item.price %></span></div>
      </div>

      <hr class="my-5">

      <div class="font-weight-bold mb-3">支払い方法</div>
      <% if current_user.selected_creditcard_id.present? %>
        <div>
          <div>
            <div><%= @selected_creditcard.masked_number %></div>
            <div>有効期限 <%= @selected_creditcard.expire_date %></div>
            <div><%= @selected_creditcard.brand %></div>
          </div>
        </div>
        <div class="mt-3">
          <%= link_to '変更する >', item_creditcards_path(@item) %>
        </div>
      <% else %>
        <%= link_to '+ 登録してください', new_item_creditcard_path(@item) %>
      <% end %>

      <hr class="my-5">

      <div class="font-weight-bold mb-3">配送先</div>
      <% if current_user.selected_destination_id.present? %>
        <div>
          <div>
            <div>〒<%= @selected_destination.postal_code %></div>
            <div><%= @selected_destination.full_address %></div>
            <div><%= @selected_destination.full_name %></div>
          </div>
        </div>
        <div class="mt-3">
          <%= link_to '変更する >', item_destinations_path(@item) %>
        </div>
      <% else %>
        <%= link_to '+ 登録してください', new_item_destination_path(@item) %>
      <% end %>

      <hr class="my-5">

      <% if !current_user.selected_creditcard_id || !current_user.selected_destination_id %>
        <span class="text-danger">配送先と支払い方法の入力を完了してください。</span>
      <% end %>

      <%= form_with url: payment_item_path(@item), method: :patch, local: true do |f| %>
        <%= f.submit '出品する', class: "btn btn-primary btn-block mt-4" %>
      <% end %>

    </div>
  </div>
</div>

app/views/front/items/payment_finish.html.erb
<p class="text-center text-success font-weight-bold mt-5">購入に成功しました!</p>
<p class="text-center"><%= link_to 'トップへ戻る', root_path %></p>

app/views/front/items/show.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2 rounded p-5" style="background-color: #FFFFFF;">
    <h3 class="text-center"><%= @item.name %></h3>

    <div class="row mt-3 mb-4">
      <div class="col-md-6">
        <%= image_tag @item.thumbnail, class: 'img-thumbnail' %>
      </div>
      <div class="col-md-6">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th>出品者</th>
              <td>
                <%= link_to @item.user_name, '#' %>
              </td>
            </tr>
            <tr>
              <th>カテゴリ</th>
              <td>
                <% @item.categories.each do |category| %>
                  <%= link_to category.name, category_path(category) %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>ブランド</th>
              <td>
                <%= link_to 'ブランド名が入ります', '#' %>
              </td>
            </tr>
            <tr>
              <th>商品の状態</th>
              <td><%= @item.condition_text %></td>
            </tr>
            <tr>
              <th>配送料の負担</th>
              <td><%= @item.delivery_fee_text %></td>
            </tr>
            <tr>
              <th>配送方法</th>
              <td></td>
            </tr>
            <tr>
              <th>配送元地域</th>
              <td><%= @item.prefecture_text %></td>
            </tr>
            <tr>
              <th>発送日の目安</th>
              <td><%= @item.days_to_ship_text %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <p class="text-center font-weight-bold" style="font-size: 2.5rem;">¥<%= @item.price %></p>

    <div class="text-center mb-5">
      <%= link_to '購入画面に進む', payment_confirm_item_path(@item), class: 'btn btn-danger btn-lg btn-block' %>
    </div>

    <p><%= @item.body %></p>
    <%= link_to 'いいね! 9', '#', class: 'badge badge-pill badge-secondary mt-5 p-3' %>

  </div>

  <% if user_signed_in? %>
    <div class="col-md-8 offset-md-2 rounded mt-4 p-5" style="background-color: #FFFFFF;">
      <%= react_component("Comment", { user_id: current_user.id, item_id: @item.id }) %>
    </div>
  <% end %>

  <div class="col-md-8 offset-md-2 rounded mt-4 p-5" style="background-color: #FFFFFF;">
    ソーシャルシェアボタンが入ります。
  </div>

  <div class="col-md-8 offset-md-2 mt-4 p-0">
    <%= link_to @item.user_name + 'さんのその他の出品', '#', class: 'font-weight-bold' %>
    <div class="row mt-3">
      <% @other_items.each do |other_item| %>
        <div class="col-md-4 mb-3">
          <%= link_to item_path(other_item) do %>
            <div class="card">
              <%= image_tag other_item.thumbnail, class: 'img-thumbnail', style: 'height: 200px' do %>
              <% end %>
              <div class="card-body">
                <span class="badge badge-secondary">¥<%= other_item.price %></span>
                <p class="card-title text-dark"><%= other_item.name %></p>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

</div>